# NEXUS
nexusUrl=http://localhost:7777/repository/maven-releases/
nexusUser=user
nexusPassword=strongpassword

# APP
appVersion=1.0.0
javaVersion=24
# OPENAPI
openApiGeneratorPluginVersion=7.6.0
# SPRING
springBootVersion=3.5.7
springDependencyManagementVersion=1.1.7
openApiGenerator=7.0.1
swagger=2.2.22
databindNullable=0.2.6
jakartaValidation=3.0.2

# LINTERS
gradlePluginAvro=1.9.1
spotbugsVersion=6.2.4

checkstyleToolVersion=11.0.0
spotbugsToolVersion=4.9.3
jacocoToolVersion=0.8.13

#DEPENDENCY
commonsLang3Version=3.18.0
confluentVersion=8.0.0
avroVersion=1.12.0
mapstructVersion=1.6.3
testcontainersVersion=1.20.3
awaitilityVersion=4.2.0
opentelemetrySpringBootVersion=2.14.0
shardingsphere=5.5.2
commonsCollections=4.5.0
ulidCreator=5.2.0
flyWay=11.11.2
logbackEncoder=8.1
testContainerKeycloak=2.1.2
