plugins {
    id "java-library"
    id "org.openapi.generator" version "${openapiGenerator}"
    id "maven-publish"
}

group = "ts.andrey"
version = "${appVersion}"
description = 'event-api'

def nexusUrl = System.getenv("NEXUS_URL") ?: project.findProperty("nexusUrl") ?: "http://localhost:7777/repository/maven-releases/"
def nexusUser = System.getenv("NEXUS_USER") ?: project.findProperty("nexusUser") ?: "admin"
def nexusPassword = System.getenv("NEXUS_PASSWORD") ?: project.findProperty("nexusPassword") ?: "admin123"

repositories {
    mavenCentral()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = "event-api"
        }
    }
    repositories {
        maven {
            name = "nexus"
            url = uri(nexusUrl)
            allowInsecureProtocol = true
            credentials {
                username = nexusUser
                password = nexusPassword
            }
        }
    }
}

dependencies {
    api "org.springframework.cloud:spring-cloud-starter-openfeign:${openfeign}"
    api "org.springframework.boot:spring-boot-starter-validation:${springValidation}"
    api "jakarta.validation:jakarta.validation-api:${jakartaValidation}"
    api "org.openapitools:jackson-databind-nullable:${jacksonNullable}"
    api "com.fasterxml.jackson.core:jackson-annotations:${jacksonAnnotation}"

    compileOnly "io.swagger.core.v3:swagger-annotations:${swagger}"
}

openApiGenerate {
    generatorName = "spring"
    inputSpec = "$projectDir/src/main/resources/openapi/event-api.yml".toString()
    outputDir = "$buildDir/generated".toString()
    apiPackage = "ts.andrey.event.api"
    modelPackage = "ts.andrey.event.model"
    invokerPackage = "ts.andrey.event.client"
    library = "spring-cloud"
    configOptions = [
            dateLibrary   : "java8",
            interfaceOnly : "true",
            useSpringBoot3: "true",
            useJakartaEe  : "true",
            useTags       : "true"
    ]
}

sourceSets {
    main {
        java {
            srcDir "$buildDir/generated/src/main/java"
        }
    }
}

compileJava.dependsOn tasks.openApiGenerate
