scrape_configs:
  - job_name: 'macos-host'
    static_configs:
      - targets: ['host.docker.internal:9100']
  - job_name: 'kafka-exporter'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: ['kafka-exporter:9308']
  - job_name: 'postgres-exporter'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]
  - job_name: 'cassandra-exporter'
    scrape_interval: 15s
    scrape_timeout: 10s
    static_configs:
      - targets: [ 'cassandra-exporter:8080' ]
  - job_name: 'event-collector'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'event-collector:8888' ]
  - job_name: 'device-collector'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'device-collector:8889' ]
  - job_name: 'failed-events-processor'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'failed-events-processor:8880' ]
  - job_name: 'device-service'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'device-service:8886' ]
  - job_name: 'event-service'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'event-service:8881' ]
  - job_name: 'orchestrator'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'orchestrator:8879' ]
  - job_name: 'router-manager-service'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'router-manager-service:9091' ]
  - job_name: 'minio'
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/minio/v2/metrics/cluster'
    static_configs:
      - targets: [ 'minio:9000' ]
