server:
  port: 8889

logging:
  level:
    org.apache.kafka: OFF
    springframework.kafka: OFF
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.postgresql: DEBUG
    org.hibernate.stat: DEBUG

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: device-collector
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf

opentelemetry:
  instrumentation:
    logback-mdc:
      enabled: true
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf
      timeout: 10000
      compression: gzip
  traces:
    exporter: otlp
  metrics:
    exporter: none
  logs:
    exporter: none
  resource-attributes:
    service.version: 1.0.0
    deployment.environment: docker
    service.name: ${spring.application.name}

spring:
  application:
    name: device-collector
  flyway:
    enabled: false
    locations: classpath:db/migration
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
#    url: jdbc:shardingsphere:classpath:sharding-config-local.yml
  jpa:
    properties:
      generate_statistics: true
    hibernate:
      query:
        in_clause_parameter_padding: true
      session:
        events:
          LOG_QUERIES_SLOWER_THAN_MS: 10
      ddl-auto: none
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    template:
      device-topic: device
      dlt-device-topic: device.DLT
      observation-enabled: true
    consumer:
      max-poll-records: 50000
      fetch-max-wait: 500
      fetch-min-size: 1024
      enable-auto-commit: false
      group-id: device-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
        avro.remove.java.properties: true
    listener:
      ack-mode: batch
      concurrency: 3
      type: batch
      idle-between-polls: 1000
      observation-enabled: true

app:
  shardingSphere:
    logicTable: t_device
    shardingColumn: device_id
    shardCount: 2
    algorithmExpression: shard$->{Math.abs(device_id.hashCode()) %% %s}
  postgres:
    retry:
      max-attempts: 3
      initial-delay: 1000
      multiplier: 5
    batch-size: 300
  dataSources:
    - url: jdbc:postgresql://localhost:5431/iot_platform
      username: myuser
      password: strongpassword
    - url: jdbc:postgresql://localhost:5432/iot_platform
      username: myuser
      password: strongpassword
  replicaDataSources:
    - url: jdbc:postgresql://localhost:5433/iot_platform
      username: myuser
      password: strongpassword
    - url: jdbc:postgresql://localhost:5434/iot_platform
      username: myuser
      password: strongpassword
