server:
  port: 8889

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: device-collector
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf

opentelemetry:
  instrumentation:
    logback-mdc:
      enabled: true
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      endpoint: http://localhost:4318
      protocol: http/protobuf
      timeout: 10000
      compression: gzip
  traces:
    exporter: otlp
  metrics:
    exporter: none
  logs:
    exporter: none
  resource-attributes:
    service.version: 1.0.0
    deployment.environment: docker
    service.name: ${spring.application.name}

spring:
  application:
    name: device-collector
  liquibase:
    enabled: false
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-config-local.yml
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers: localhost:9092
    template:
      device-topic: device
      observation-enabled: true
    consumer:
      max-poll-records: 50000
      fetch-max-wait: 500
      fetch-min-size: 1024
      enable-auto-commit: false
      group-id: device-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
        avro.remove.java.properties: true
    listener:
      ack-mode: batch
      concurrency: 3
      type: batch
      idle-between-polls: 1000
      observation-enabled: true

app:
  dataSources:
    - url: jdbc:postgresql://localhost:5431/iot_platform
      username: myuser
      password: strongpassword
    - url: jdbc:postgresql://localhost:5432/iot_platform
      username: myuser
      password: strongpassword

shardingRule:
  tables:
    tdevice:
      actualDataNodes: shard${0..1}.tdevice
      tableStrategy:
        none:
      databaseStrategy:
        inline:
          shardingColumn: deviceid
          algorithm-expression: shard{(deviceid.hashCode() % 2 + 2) % 2}
