import com.github.spotbugs.snom.SpotBugsTask

plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.4'
    id 'io.spring.dependency-management' version '1.1.7'
    id "com.github.davidmc24.gradle.plugin.avro" version "1.9.1"
    id 'com.github.spotbugs' version '6.0.7'
    id 'jacoco'
    id 'checkstyle'
}

group = 'ts.andrey'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

avro {
    fieldVisibility = "PRIVATE"
    createSetters = false
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    maven { url "https://packages.confluent.io/maven/" }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    implementation 'org.springframework.boot:spring-boot-starter-data-cassandra'

    implementation 'org.liquibase:liquibase-core'
    implementation 'org.liquibase.ext:liquibase-cassandra:4.26.0'

    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.apache.commons:commons-lang3:3.18.0'
    implementation 'io.confluent:kafka-avro-serializer:7.5.0'
    implementation 'org.apache.avro:avro:1.11.4'
    implementation 'io.confluent:kafka-schema-registry-client:7.5.0'

    implementation 'org.mapstruct:mapstruct:1.6.3'

    compileOnly 'org.projectlombok:lombok'

    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.boot:spring-boot-testcontainers'
    testImplementation "org.testcontainers:cassandra:1.20.3"
    testImplementation 'org.springframework.kafka:spring-kafka-test'
    testImplementation 'org.testcontainers:junit-jupiter'
    testImplementation 'org.testcontainers:kafka'
    testImplementation 'org.awaitility:awaitility:4.2.0'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testCompileOnly 'org.projectlombok:lombok'

    testAnnotationProcessor 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
}

checkstyle {
    toolVersion = '10.12.3'
    configFile = file("$rootDir/config/checkstyle/checkstyle.xml")
    configProperties = [
            'checkstyle.suppressions.file': "$rootDir/config/checkstyle/exclude-filter.xml"
    ]
    showViolations = true
    ignoreFailures = false
    maxWarnings = 0
}

spotbugs {
    toolVersion = '4.8.3'
    ignoreFailures = true
    showProgress = true
    effort = 'max'
    reportLevel = 'low'
    excludeFilter = file("$rootDir/config/spotbugs/exclude-filter.xml")
}

tasks.withType(SpotBugsTask).configureEach {
    reports {
        xml.required = false
        html.required = true
    }
}

jacoco {
    toolVersion = "0.8.11"
}

jacocoTestReport {
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, excludes: [
                    '**/cassandra/**',
                    '**/configuration/**',
                    '**/controller/**',
                    '**/exception/**',
                    '**/*EventCollectorApplication*'
            ])
        }))
    }
}

tasks.register('jacocoMergedReport', JacocoReport) {
    dependsOn 'test'

    executionData fileTree(project.rootDir.absolutePath).include("**/build/jacoco/*.exec")

    sourceDirectories.from = files(sourceSets.main.allSource.srcDirs)
    classDirectories.from = files(sourceSets.main.output)

    reports {
        html.required = true
        xml.required = false
        csv.required = false
    }
}


configurations.configureEach {
    exclude group: 'org.slf4j', module: 'slf4j-simple'
}

tasks.named('test') {
    useJUnitPlatform()
}
