plugins {
    id 'java'
    id 'org.springframework.boot' version "${springBootVersion}"
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}"
    id "com.github.davidmc24.gradle.plugin.avro" version "${gradlePluginAvro}"
    id 'com.github.spotbugs' version "${spotbugsVersion}"
    id 'jacoco'
    id 'checkstyle'
}

group = 'ts.andrey'
version = "${appVersion}"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of("${javaVersion}")
    }
}

avro {
    fieldVisibility = "PRIVATE"
    createSetters = false
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
    maven { url "https://packages.confluent.io/maven/" }
}

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web"
    implementation "org.springframework.boot:spring-boot-starter-actuator"
    implementation "io.micrometer:micrometer-registry-prometheus"

    implementation "org.springframework.boot:spring-boot-starter-data-cassandra"

    implementation "org.springframework.kafka:spring-kafka"
    implementation "org.apache.commons:commons-lang3:${commonsLang3Version}"
    implementation "io.confluent:kafka-avro-serializer:${confluentVersion}"
    implementation "org.apache.avro:avro:${avroVersion}"
    implementation "io.confluent:kafka-schema-registry-client:${confluentVersion}"

    implementation "org.mapstruct:mapstruct:${mapstructVersion}"

    compileOnly "org.projectlombok:lombok"
    annotationProcessor "org.projectlombok:lombok"
    annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.springframework.boot:spring-boot-testcontainers"
    testImplementation "org.testcontainers:cassandra:${testcontainersVersion}"
    testImplementation "org.springframework.kafka:spring-kafka-test"
    testImplementation "org.testcontainers:junit-jupiter"
    testImplementation "org.testcontainers:kafka"
    testImplementation "org.awaitility:awaitility:${awaitilityVersion}"

    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
    testCompileOnly "org.projectlombok:lombok"
    testAnnotationProcessor "org.projectlombok:lombok"
    testAnnotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"
}

checkstyle {
    toolVersion = "${checkstyleToolVersion}"
    configFile = file("$rootDir/config/checkstyle/checkstyle.xml")
    configProperties = [
            'checkstyle.suppressions.file': "$rootDir/config/checkstyle/exclude-filter.xml"
    ]
    showViolations = true
    ignoreFailures = false
    maxWarnings = 0
}

spotbugs {
    toolVersion = "${spotbugsToolVersion}"
    ignoreFailures = true
    showProgress = true
    effort = 'max'
    reportLevel = 'low'
    excludeFilter = file("$rootDir/config/spotbugs/exclude-filter.xml")
}


jacoco {
    toolVersion = "${jacocoToolVersion}"
    reportsDirectory = layout.buildDirectory.dir('reports/jacoco')
}

jacocoTestReport {
    reports {
        xml.required = false
        html.required = true
        csv.required = false
    }

    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    '**/cassandra/**',
                    '**/configuration/**',
                    '**/controller/**',
                    '**/exception/**',
                    '**/*EventCollectorApplication*'
            ])
        }))
    }
}

configurations.configureEach {
    exclude group: 'org.slf4j', module: 'slf4j-simple'
}

tasks.named('test') {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

bootJar {
    archiveFileName = "app.jar"
}
