// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: roma.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RouterManagerService_SendCommand_FullMethodName  = "/ts.andrey.routermanager.RouterManagerService/SendCommand"
	RouterManagerService_PollCommands_FullMethodName = "/ts.andrey.routermanager.RouterManagerService/PollCommands"
	RouterManagerService_AckCommand_FullMethodName   = "/ts.andrey.routermanager.RouterManagerService/AckCommand"
)

// RouterManagerServiceClient is the client API for RouterManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouterManagerServiceClient interface {
	SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error)
	PollCommands(ctx context.Context, in *PollCommandsRequest, opts ...grpc.CallOption) (*PollCommandsResponse, error)
	AckCommand(ctx context.Context, in *AckCommandRequest, opts ...grpc.CallOption) (*AckCommandResponse, error)
}

type routerManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterManagerServiceClient(cc grpc.ClientConnInterface) RouterManagerServiceClient {
	return &routerManagerServiceClient{cc}
}

func (c *routerManagerServiceClient) SendCommand(ctx context.Context, in *SendCommandRequest, opts ...grpc.CallOption) (*SendCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendCommandResponse)
	err := c.cc.Invoke(ctx, RouterManagerService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerManagerServiceClient) PollCommands(ctx context.Context, in *PollCommandsRequest, opts ...grpc.CallOption) (*PollCommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollCommandsResponse)
	err := c.cc.Invoke(ctx, RouterManagerService_PollCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerManagerServiceClient) AckCommand(ctx context.Context, in *AckCommandRequest, opts ...grpc.CallOption) (*AckCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckCommandResponse)
	err := c.cc.Invoke(ctx, RouterManagerService_AckCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterManagerServiceServer is the server API for RouterManagerService service.
// All implementations must embed UnimplementedRouterManagerServiceServer
// for forward compatibility.
type RouterManagerServiceServer interface {
	SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error)
	PollCommands(context.Context, *PollCommandsRequest) (*PollCommandsResponse, error)
	AckCommand(context.Context, *AckCommandRequest) (*AckCommandResponse, error)
	mustEmbedUnimplementedRouterManagerServiceServer()
}

// UnimplementedRouterManagerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRouterManagerServiceServer struct{}

func (UnimplementedRouterManagerServiceServer) SendCommand(context.Context, *SendCommandRequest) (*SendCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedRouterManagerServiceServer) PollCommands(context.Context, *PollCommandsRequest) (*PollCommandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollCommands not implemented")
}
func (UnimplementedRouterManagerServiceServer) AckCommand(context.Context, *AckCommandRequest) (*AckCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AckCommand not implemented")
}
func (UnimplementedRouterManagerServiceServer) mustEmbedUnimplementedRouterManagerServiceServer() {}
func (UnimplementedRouterManagerServiceServer) testEmbeddedByValue()                              {}

// UnsafeRouterManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterManagerServiceServer will
// result in compilation errors.
type UnsafeRouterManagerServiceServer interface {
	mustEmbedUnimplementedRouterManagerServiceServer()
}

func RegisterRouterManagerServiceServer(s grpc.ServiceRegistrar, srv RouterManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedRouterManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RouterManagerService_ServiceDesc, srv)
}

func _RouterManagerService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterManagerServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterManagerService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterManagerServiceServer).SendCommand(ctx, req.(*SendCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterManagerService_PollCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterManagerServiceServer).PollCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterManagerService_PollCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterManagerServiceServer).PollCommands(ctx, req.(*PollCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RouterManagerService_AckCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterManagerServiceServer).AckCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RouterManagerService_AckCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterManagerServiceServer).AckCommand(ctx, req.(*AckCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RouterManagerService_ServiceDesc is the grpc.ServiceDesc for RouterManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RouterManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ts.andrey.routermanager.RouterManagerService",
	HandlerType: (*RouterManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommand",
			Handler:    _RouterManagerService_SendCommand_Handler,
		},
		{
			MethodName: "PollCommands",
			Handler:    _RouterManagerService_PollCommands_Handler,
		},
		{
			MethodName: "AckCommand",
			Handler:    _RouterManagerService_AckCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "roma.proto",
}
