// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: roma.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterSerial  string                 `protobuf:"bytes,1,opt,name=router_serial,json=routerSerial,proto3" json:"router_serial,omitempty"`
	CommandType   string                 `protobuf:"bytes,2,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandRequest) Reset() {
	*x = SendCommandRequest{}
	mi := &file_roma_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandRequest) ProtoMessage() {}

func (x *SendCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roma_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandRequest.ProtoReflect.Descriptor instead.
func (*SendCommandRequest) Descriptor() ([]byte, []int) {
	return file_roma_proto_rawDescGZIP(), []int{0}
}

func (x *SendCommandRequest) GetRouterSerial() string {
	if x != nil {
		return x.RouterSerial
	}
	return ""
}

func (x *SendCommandRequest) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *SendCommandRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SendCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Created       int32                  `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandResponse) Reset() {
	*x = SendCommandResponse{}
	mi := &file_roma_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandResponse) ProtoMessage() {}

func (x *SendCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roma_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandResponse.ProtoReflect.Descriptor instead.
func (*SendCommandResponse) Descriptor() ([]byte, []int) {
	return file_roma_proto_rawDescGZIP(), []int{1}
}

func (x *SendCommandResponse) GetCreated() int32 {
	if x != nil {
		return x.Created
	}
	return 0
}

type PollCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterSerial  string                 `protobuf:"bytes,1,opt,name=router_serial,json=routerSerial,proto3" json:"router_serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollCommandsRequest) Reset() {
	*x = PollCommandsRequest{}
	mi := &file_roma_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollCommandsRequest) ProtoMessage() {}

func (x *PollCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roma_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollCommandsRequest.ProtoReflect.Descriptor instead.
func (*PollCommandsRequest) Descriptor() ([]byte, []int) {
	return file_roma_proto_rawDescGZIP(), []int{2}
}

func (x *PollCommandsRequest) GetRouterSerial() string {
	if x != nil {
		return x.RouterSerial
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RouterSerial  string                 `protobuf:"bytes,2,opt,name=router_serial,json=routerSerial,proto3" json:"router_serial,omitempty"`
	CommandType   string                 `protobuf:"bytes,3,opt,name=command_type,json=commandType,proto3" json:"command_type,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	AckedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=acked_at,json=ackedAt,proto3" json:"acked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_roma_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_roma_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_roma_proto_rawDescGZIP(), []int{3}
}

func (x *Command) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Command) GetRouterSerial() string {
	if x != nil {
		return x.RouterSerial
	}
	return ""
}

func (x *Command) GetCommandType() string {
	if x != nil {
		return x.CommandType
	}
	return ""
}

func (x *Command) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Command) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Command) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Command) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Command) GetAckedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AckedAt
	}
	return nil
}

type PollCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollCommandsResponse) Reset() {
	*x = PollCommandsResponse{}
	mi := &file_roma_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollCommandsResponse) ProtoMessage() {}

func (x *PollCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roma_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollCommandsResponse.ProtoReflect.Descriptor instead.
func (*PollCommandsResponse) Descriptor() ([]byte, []int) {
	return file_roma_proto_rawDescGZIP(), []int{4}
}

func (x *PollCommandsResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type AckCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterSerial  string                 `protobuf:"bytes,1,opt,name=router_serial,json=routerSerial,proto3" json:"router_serial,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckCommandRequest) Reset() {
	*x = AckCommandRequest{}
	mi := &file_roma_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckCommandRequest) ProtoMessage() {}

func (x *AckCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_roma_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckCommandRequest.ProtoReflect.Descriptor instead.
func (*AckCommandRequest) Descriptor() ([]byte, []int) {
	return file_roma_proto_rawDescGZIP(), []int{5}
}

func (x *AckCommandRequest) GetRouterSerial() string {
	if x != nil {
		return x.RouterSerial
	}
	return ""
}

func (x *AckCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type AckCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckCommandResponse) Reset() {
	*x = AckCommandResponse{}
	mi := &file_roma_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckCommandResponse) ProtoMessage() {}

func (x *AckCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_roma_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckCommandResponse.ProtoReflect.Descriptor instead.
func (*AckCommandResponse) Descriptor() ([]byte, []int) {
	return file_roma_proto_rawDescGZIP(), []int{6}
}

func (x *AckCommandResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_roma_proto protoreflect.FileDescriptor

const file_roma_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"roma.proto\x12\x17ts.andrey.routermanager\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x8f\x01\n" +
	"\x12SendCommandRequest\x12#\n" +
	"\rrouter_serial\x18\x01 \x01(\tR\frouterSerial\x12!\n" +
	"\fcommand_type\x18\x02 \x01(\tR\vcommandType\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\"/\n" +
	"\x13SendCommandResponse\x12\x18\n" +
	"\acreated\x18\x01 \x01(\x05R\acreated\":\n" +
	"\x13PollCommandsRequest\x12#\n" +
	"\rrouter_serial\x18\x01 \x01(\tR\frouterSerial\"\xd3\x02\n" +
	"\aCommand\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rrouter_serial\x18\x02 \x01(\tR\frouterSerial\x12!\n" +
	"\fcommand_type\x18\x03 \x01(\tR\vcommandType\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x123\n" +
	"\asent_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x125\n" +
	"\backed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\aackedAt\"T\n" +
	"\x14PollCommandsResponse\x12<\n" +
	"\bcommands\x18\x01 \x03(\v2 .ts.andrey.routermanager.CommandR\bcommands\"W\n" +
	"\x11AckCommandRequest\x12#\n" +
	"\rrouter_serial\x18\x01 \x01(\tR\frouterSerial\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\",\n" +
	"\x12AckCommandResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xd4\x02\n" +
	"\x14RouterManagerService\x12h\n" +
	"\vSendCommand\x12+.ts.andrey.routermanager.SendCommandRequest\x1a,.ts.andrey.routermanager.SendCommandResponse\x12k\n" +
	"\fPollCommands\x12,.ts.andrey.routermanager.PollCommandsRequest\x1a-.ts.andrey.routermanager.PollCommandsResponse\x12e\n" +
	"\n" +
	"AckCommand\x12*.ts.andrey.routermanager.AckCommandRequest\x1a+.ts.andrey.routermanager.AckCommandResponseB'Z%router-manager-service/internal/pb;pbb\x06proto3"

var (
	file_roma_proto_rawDescOnce sync.Once
	file_roma_proto_rawDescData []byte
)

func file_roma_proto_rawDescGZIP() []byte {
	file_roma_proto_rawDescOnce.Do(func() {
		file_roma_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_roma_proto_rawDesc), len(file_roma_proto_rawDesc)))
	})
	return file_roma_proto_rawDescData
}

var file_roma_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_roma_proto_goTypes = []any{
	(*SendCommandRequest)(nil),    // 0: ts.andrey.routermanager.SendCommandRequest
	(*SendCommandResponse)(nil),   // 1: ts.andrey.routermanager.SendCommandResponse
	(*PollCommandsRequest)(nil),   // 2: ts.andrey.routermanager.PollCommandsRequest
	(*Command)(nil),               // 3: ts.andrey.routermanager.Command
	(*PollCommandsResponse)(nil),  // 4: ts.andrey.routermanager.PollCommandsResponse
	(*AckCommandRequest)(nil),     // 5: ts.andrey.routermanager.AckCommandRequest
	(*AckCommandResponse)(nil),    // 6: ts.andrey.routermanager.AckCommandResponse
	(*structpb.Struct)(nil),       // 7: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_roma_proto_depIdxs = []int32{
	7, // 0: ts.andrey.routermanager.SendCommandRequest.payload:type_name -> google.protobuf.Struct
	7, // 1: ts.andrey.routermanager.Command.payload:type_name -> google.protobuf.Struct
	8, // 2: ts.andrey.routermanager.Command.created_at:type_name -> google.protobuf.Timestamp
	8, // 3: ts.andrey.routermanager.Command.sent_at:type_name -> google.protobuf.Timestamp
	8, // 4: ts.andrey.routermanager.Command.acked_at:type_name -> google.protobuf.Timestamp
	3, // 5: ts.andrey.routermanager.PollCommandsResponse.commands:type_name -> ts.andrey.routermanager.Command
	0, // 6: ts.andrey.routermanager.RouterManagerService.SendCommand:input_type -> ts.andrey.routermanager.SendCommandRequest
	2, // 7: ts.andrey.routermanager.RouterManagerService.PollCommands:input_type -> ts.andrey.routermanager.PollCommandsRequest
	5, // 8: ts.andrey.routermanager.RouterManagerService.AckCommand:input_type -> ts.andrey.routermanager.AckCommandRequest
	1, // 9: ts.andrey.routermanager.RouterManagerService.SendCommand:output_type -> ts.andrey.routermanager.SendCommandResponse
	4, // 10: ts.andrey.routermanager.RouterManagerService.PollCommands:output_type -> ts.andrey.routermanager.PollCommandsResponse
	6, // 11: ts.andrey.routermanager.RouterManagerService.AckCommand:output_type -> ts.andrey.routermanager.AckCommandResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_roma_proto_init() }
func file_roma_proto_init() {
	if File_roma_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_roma_proto_rawDesc), len(file_roma_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_roma_proto_goTypes,
		DependencyIndexes: file_roma_proto_depIdxs,
		MessageInfos:      file_roma_proto_msgTypes,
	}.Build()
	File_roma_proto = out.File
	file_roma_proto_goTypes = nil
	file_roma_proto_depIdxs = nil
}
