server:
  port: 8888
spring:
  application:
    name: event-collector
  kafka:
    bootstrap-servers: localhost:9092
    template:
      events-topic: events
      dlt-events-topic: events.DLT
      device-topic: device-id-topic
      dlt-device-topic: device-id-topic.DLT
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8081
        auto.register.schemas: true
    consumer:
      group-id: device-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
        use.latest.version: true
    listener:
      ack-mode: batch
      concurrency: 3

  cassandra:
    contact-points: localhost
    port: 9042
    local-datacenter: datacenter1
    keyspace-name: iot_service
    schema-action: CREATE_IF_NOT_EXISTS

app:
  cache:
    expiration:
      seconds: 30
