# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             all                                     trust
host    all             all             postgres1r              trust
host    all             all             postgres2r              trust
host    all             all             172.18.0.0/16           md5
host    replication     all             172.18.0.0/16           md5
host    replication     replicator      172.18.0.0/16           md5
