@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

AddElementTag("microservice", $bgColor="#E6F3F7", $fontColor="#333333", $borderColor="#3F668F")
AddElementTag("storage", $bgColor="#F7E9E6", $fontColor="#333333", $borderColor="#8F3F3F")
AddElementTag("queue", $bgColor="#E6F7E6", $fontColor="#333333", $borderColor="#3F8F5F")

Container_Boundary(app, "event-collector") {
    Component(consumer, "DeviceEventConsumer", "Кафка-консьюмер", "class")
    Component(collector, "CollectorFacade", "Оркестратор процесса", "class")
    Component(deduplicate_service, "DeduplicateService", "Поиск новых девайсов", "class")
    Component(device_event_service, "DeviceEventService", "Обработка событий", "class")
    Component(cache, "SimpleCache", "In-memory кеш", "storage")
    Component(event_data_service, "DeviceEventDataService", "repository", "class")
    Component(device_service, "DeviceService", "отправка в kafka", "class")
    Component(producer, "DeviceEventProducer", "Кафка-продюсер", "class")
}

System_Ext(kafka, "Apache Kafka", "Топик device-events", "queue")
System_Ext(schema_reg, "Schema Registry", "Avro-схемы", "storage")
System_Ext(cassandra, "Cassandra", "Постоянное хранилище", "storage")

Rel(kafka, consumer, "Чтение сообщений", "Kafka")
Rel(consumer, schema_reg, "Получение схемы", "HTTP")
Rel(consumer, collector, "Передача сообщения", "Java-вызов")

Rel(collector, deduplicate_service, "Поиск новых девайсов", "Java-вызов")
Rel(collector, device_event_service, "Обработка событий", "Java-вызов")
Rel(collector, device_service, "обработка новых девайсов", "Java-вызов")

Rel(deduplicate_service, cache, "Проверка в cache", "Java-вызов")
Rel(deduplicate_service, event_data_service, "Проверка в cassandra", "Java-вызов")
Rel(event_data_service, cassandra, "Проверка в cassandra", "CQL")

Rel(device_event_service, event_data_service, "Сохранить все события]", "Java-вызов")
Rel(event_data_service, cassandra, "Сохранить события", "CQL")

Rel(device_event_service, cache, "Кешировать устройства", "Java-вызов")
Rel(device_service, producer, "Отправить новые устройства в топик", "Java-вызов")

@enduml
