@startuml
actor KafkaBroker
participant "DeviceEventConsumer" as DEC  #lightblue
participant "SchemaRegistry" as AVRO
participant "CollectorService" as ECS  #lightblue
participant "DeviceEventService" as DES  #lightblue
participant "SimpleCache" as CACHE #lightblue
participant "Cassandra" as DB
participant "KafkaProducer" as KP  #lightblue

KafkaBroker --> DEC : события в Avro (DeviceEvents)
DEC -> AVRO : десериализация Avro
AVRO -> DEC : DeviceEvents
DEC -> ECS : DeviceEvents
ECS -> DES : DeviceEvents

alt Проверка дедупликации
    DES -> CACHE : проверка deviceId
    CACHE -> DES : существует?
    opt Если дубликат
        DES -> DB : сохранить DeviceEvents
        DES -> CACHE : актуализировать cache
    end
    DES -> DB : проверка deviceId
    DB -> DES : существует?
    opt Если дубликат
            DES -> DB : сохранить DeviceEvents
            DES -> CACHE : добавить в cache
    end
end
    DES -> ECS : не обработанные DeviceEvents
    ECS --> KP : отправить в "device-id" topic
    ECS -> CACHE : добавить в cache
    ECS -> DB : сохранить событие

@enduml
