{
  "type": "record",
  "name": "DeviceEvent",
  "namespace": "com.nashkod.avro",
  "fields": [
    {
      "name": "eventId",
      "type": "string"
    },
    {
      "name": "timestamp",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "type",
      "type": {
        "type": "enum",
        "name": "EventType",
        "symbols": [
          "TEMPERATURE",
          "HUMIDITY",
          "STATUS",
          "ERROR"
        ]
      }
    },
    {
      "name": "payload",
      "type": "string"
    },
    {
      "name": "device",
      "type": {
        "type": "record",
        "name": "Device",
        "fields": [
          {
            "name": "deviceId",
            "type": "string"
          },
          {
            "name": "deviceType",
            "type": "string"
          },
          {
            "name": "meta",
            "type": "string"
          },
          {
            "name": "createdAt",
            "type": {
              "type": "long",
              "logicalType": "timestamp-millis"
            }
          }
        ]
      }
    }
  ]
}
