@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

AddElementTag("microservice", $bgColor="#E6F3F7", $fontColor="#333333", $borderColor="#3F668F")
AddElementTag("storage", $bgColor="#F7E9E6", $fontColor="#333333", $borderColor="#8F3F3F")
AddElementTag("queue", $bgColor="#E6F7E6", $fontColor="#333333", $borderColor="#3F8F5F")

Container_Boundary(app, "event-collector") {
    Component(consumer, "DeviceConsumer", "Кафка-консьюмер", "class")
    Component(device_service, "DeviceService", "Оркестратор процесса", "class")
    Component(device_data_service, "DeviceDataService", "repository", "class")
}

System_Ext(kafka, "Apache Kafka", "Топик device-events", "queue")
System_Ext(schema_reg, "Schema Registry", "Avro-схемы", "storage")
System_Ext(postgres, "Postgres", "Постоянное хранилище", "storage")

Rel(kafka, consumer, "Чтение сообщений", "Kafka")
Rel(consumer, schema_reg, "Получение схемы", "HTTP")
Rel(consumer, device_service, "Передача сообщения", "Java-вызов")

Rel(device_service, device_data_service, "Сохранение\Обновление", "Java-вызов")
Rel(device_data_service, postgres, "Сохранение\Обновление", "Java-вызов")

@enduml
