{
 "title": "EventCollectorMetrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Events success",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "events_processed_success_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Event fail (DLT)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "events_processed_error_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Device success (saved)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "device_processed_success_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Postgres SHARD-1",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "device_postgres_success_total{shard=\"shard-0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Postgres SHARD-2",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "device_postgres_success_total{shard=\"shard-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device fail (DLT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "device_processed_error_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Postgres fail",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "targets": [
    { "expr": "device_postgres_error_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cassandra Success",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "events_cassandra_success_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cassandra fail",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "events_cassandra_fail_total", "legendFormat": "__auto" }
   ]
  }
 ]
}