{
 "title": "Orchestrator Dashboard",
 "tags": [
  "orchestrator",
  "monitoring",
  "api"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Время ответа по endpoint (p50/p95/p99)",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket{application=\"orchestrator\", uri!~\"/actuator.*\"}[5m])) by (le, uri)) * 1000",
     "legendFormat": "{{uri}} - p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"orchestrator\", uri!~\"/actuator.*\"}[5m])) by (le, uri)) * 1000",
     "legendFormat": "{{uri}} - p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"orchestrator\", uri!~\"/actuator.*\"}[5m])) by (le, uri)) * 1000",
     "legendFormat": "{{uri}} - p99"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"orchestrator\", outcome=\"SUCCESS\",uri!~\"/actuator.*\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"orchestrator\", uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "Success Rate"
    }
   ]
  },
  {
   "title": "Ошибки по типам (4xx/5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{application=\"orchestrator\", outcome!=\"SUCCESS\",uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Router Manager - команды",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(orchestrator_router_command_success_total[5m]))",
     "legendFormat": "Send Command - Success"
    },
    {
     "expr": "sum(rate(orchestrator_router_command_fail_total[5m]))",
     "legendFormat": "Send Command - Fail"
    },
    {
     "expr": "sum(rate(orchestrator_router_poll_success_total[5m]))",
     "legendFormat": "Poll Commands - Success"
    },
    {
     "expr": "sum(rate(orchestrator_router_poll_fail_total[5m]))",
     "legendFormat": "Poll Commands - Fail"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 7, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{application=\"orchestrator\", uri!~\"/actuator.*\"}",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Error Rate по endpoint",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (uri) (rate(http_server_requests_seconds_count{application=\"orchestrator\", outcome!=\"SUCCESS\",uri!~\"/actuator.*\"}[5m])) / sum by (uri) (rate(http_server_requests_seconds_count{application=\"orchestrator\", uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Топ-10 по Latency (p95)",
   "type": "table",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(10,\n  histogram_quantile(0.99,\n    sum by (le, uri) (\n      rate(http_server_requests_seconds_bucket{\n        application=\"orchestrator\", \n        uri!~\"/actuator.*\",\n        le!=\"0.0\"\n      }[10m])\n    )\n  ) * 1000\n)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Распределение latency по bucket'ам",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_bucket{application=\"orchestrator\", uri!~\"/actuator.*\",le=\"0.1\"}[5m])) / sum(rate(http_server_requests_seconds_count{application=\"orchestrator\", uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "< 100ms"
    },
    {
     "expr": "(sum(rate(http_server_requests_seconds_bucket{application=\"orchestrator\", uri!~\"/actuator.*\",le=\"0.5\"}[5m])) - sum(rate(http_server_requests_seconds_bucket{application=\"orchestrator\", uri!~\"/actuator.*\",le=\"0.1\"}[5m]))) / sum(rate(http_server_requests_seconds_count{application=\"orchestrator\", uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "100-500ms"
    },
    {
     "expr": "(sum(rate(http_server_requests_seconds_bucket{application=\"orchestrator\", uri!~\"/actuator.*\",le=\"1.0\"}[5m])) - sum(rate(http_server_requests_seconds_bucket{application=\"orchestrator\", uri!~\"/actuator.*\",le=\"0.5\"}[5m]))) / sum(rate(http_server_requests_seconds_count{application=\"orchestrator\", uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "500ms-1s"
    },
    {
     "expr": "(sum(rate(http_server_requests_seconds_count{application=\"orchestrator\", uri!~\"/actuator.*\"}[5m])) - sum(rate(http_server_requests_seconds_bucket{application=\"orchestrator\", uri!~\"/actuator.*\",le=\"1.0\"}[5m]))) / sum(rate(http_server_requests_seconds_count{application=\"orchestrator\", uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "> 1s"
    }
   ]
  },
  {
   "title": "Топ-10 endpoint по RPS",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(10, sum by (uri) (rate(http_server_requests_seconds_count{application=\"orchestrator\", uri!~\"/actuator.*\"}[10m])))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Нагрузка по методам (GET/POST/PUT)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_server_requests_seconds_count{application=\"orchestrator\", uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Топ 5 исключений",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (exception) (rate(orchestrator_fail_total[5m])))",
     "legendFormat": "{{exception}}"
    }
   ]
  },
  {
   "title": "Saga и Redis",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(orchestrator_saga_success_total[5m]))",
     "legendFormat": "Saga - Success"
    },
    {
     "expr": "sum(rate(orchestrator_saga_fail_total[5m]))",
     "legendFormat": "Saga - Fail"
    },
    {
     "expr": "sum(rate(orchestrator_saga_rollback_total[5m]))",
     "legendFormat": "Saga - Rollback"
    },
    {
     "expr": "sum(rate(orchestrator_redis_success_total[5m]))",
     "legendFormat": "Redis - Success"
    },
    {
     "expr": "sum(rate(orchestrator_redis_fail_total[5m]))",
     "legendFormat": "Redis - Fail"
    }
   ]
  },
  {
   "title": "Общая нагрузка (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"orchestrator\", outcome=\"SUCCESS\",uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "Успешные запросы"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"orchestrator\", outcome!=\"SUCCESS\",uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "Ошибки запросов"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"orchestrator\", uri!~\"/actuator.*\"}[5m]))",
     "legendFormat": "Всего запросов"
    }
   ]
  },
  {
   "title": "Активные (параллельные) запросы",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(http_server_requests_active_seconds_gcount{application=\"orchestrator\", uri!~\"/actuator.*\"}[5m])",
     "legendFormat": "{{uri}} - Active"
    }
   ]
  }
 ]
}