@startuml
actor "Admin" as Admin
participant "Command Service (Go)" as CS #lightblue
participant "Command Storage" as Storage #lightblue
participant "Router" as Router

Admin -> CS : gRPC /api/v1/send-command
CS -> Storage : Сохранить команду (PENDING)

Router -> CS : gRPC /api/v1/commands/poll
CS -> Storage : Получить команды для router_id
CS -> Storage : Обновить статус команд (SENT, sent_at)
CS -> Router : Отдать команды

Router -> CS : gRPC /api/v1/commands/ack
CS -> Storage : Обновить команду (ACKED, acked_at)
CS -> Router : Подтверждение
@enduml
