services:
  iot-avro:
    restart: "no"
    build:
      context: ../iot-avro
    container_name: iot-avro
    entrypoint: ["./gradlew", "--no-daemon", "publish"]
    env_file:
      - .env
    networks:
      - infrastructure_iot_network
  iot-common:
    restart: "no"
    build:
      context: ../iot-common
    container_name: iot-common
    entrypoint: ["./gradlew", "--no-daemon", "publish"]
    env_file:
      - .env
    networks:
      - infrastructure_iot_network
  device-api:
    restart: "no"
    build:
      context: ../device-api
    container_name: device-api
    entrypoint: ["./gradlew", "--no-daemon", "publish"]
    env_file:
      - .env
    networks:
      - infrastructure_iot_network
networks:
  infrastructure_iot_network:
    external: true
