services:
  kafka-producer:
    build:
      dockerfile: ../kafka-producer/Dockerfile.local
  device-collector:
    build:
      dockerfile: ../device-collector/Dockerfile.local
  device-service:
    build:
      dockerfile: ../device-service/Dockerfile.local
  event-collector:
    build:
      dockerfile: ../event-collector/Dockerfile.local
  failed-events-processor:
    build:
      dockerfile: ../failed-events-processor/Dockerfile.local
