services:
  iot-avro:
    restart: "no"
    build:
      context: ../iot-avro
    container_name: iot-avro
    entrypoint: [ "./gradlew", "--no-daemon", "clean", "build", "publish" ]
    env_file:
      - .env
    networks:
      - infrastructure_iot_network
  iot-common:
    restart: "no"
    build:
      context: ../iot-common
    container_name: iot-common
    entrypoint: [ "./gradlew", "--no-daemon", "clean", "build", "publish" ]
    env_file:
      - .env
    networks:
      - infrastructure_iot_network
  device-api:
    restart: "no"
    build:
      context: ../device-api
    container_name: device-api
    entrypoint: [ "./gradlew", "--no-daemon", "clean", "build", "publish" ]
    env_file:
      - .env
    networks:
      - infrastructure_iot_network
  router-manager-proto-client:
    restart: "no"
    build:
      context: ../router-manager-proto-client
    container_name: router-manager-proto-client
    entrypoint: [ "./gradlew", "--no-daemon", "clean", "build", "publish" ]
    env_file:
      - .env
    networks:
      - infrastructure_iot_network
networks:
  infrastructure_iot_network:
    external: true
