@startuml Containers
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container_Boundary(platform, "IoT Platform") {
    Container(router, "Router", "GO", "Устройство")
    Container(routermanager, "Router Manager", "GO", "Управление устройствами")
    Container(eventcollector, "Event Collector", "Spring Boot", "Сбор событий")
    Container(cassandra, "Cassandra", "events", "Хранение событий") #gray
    Container(eventservice, "Event Service", "Spring Boot", "Сбор событий")
    Container(devicecollector, "Device Collector", "Spring Boot", "Сбор устройств")
    Container(routermanagerdb, "Router Manager DataBase", "Postgres", "Хранение команд") #gray
    Container(devicedb, "Device DataBase", "Postgres", "Хранение устройств") #gray
    Container(devser, "Device Service", "Spring Boot", "CRUD над devices")
    Container(kafkaproducer, "Kafka Producer", "Spring Boot", "Системный сервис для тестирования") #333355
    Container(kafka, "Kafka", "Avro", "Хранение событий и устройств") #gray
    Container(keycloak, "keycloak", "keycloak", "Авторизация") #gray
    Container(orchestrator, "Orchestrator", "Spring Boot", "Оркестрация")
}
Rel("orchestrator", "devser", "CRUD device")
Rel("orchestrator", "routermanager", "Создание команд")
Rel("orchestrator", "keycloak", "JWT")

Rel("kafkaproducer", "kafka", "event")
Rel("kafkaproducer", "keycloak", "JWT")
Rel("devser", "keycloak", "JWT")
Rel("kafka", "eventcollector", "event")
Rel("eventcollector", "cassandra", "event")
Rel("eventservice", "cassandra", "get event")
Rel("eventcollector", "kafka", "device")
Rel("kafka", "devicecollector", "device")
Rel("devicecollector", "devicedb", "device")
Rel("devser", "devicedb", "CRUD над devices")

Rel("router", "routermanager", "POLL")
Rel("router", "routermanager", "ACK")
Rel("routermanager", "routermanagerdb", "команды и статус")

@enduml
