plugins {
    id "java-library"
    id "com.github.davidmc24.gradle.plugin.avro" version "${gradlePluginAvro}"
    id "maven-publish"
}

group = "ts.andrey"
version = "${appVersion}"
description = 'iot-avro'

repositories {
    mavenCentral()
    maven { url "https://packages.confluent.io/maven/" }
}

avro {
    fieldVisibility = "PRIVATE"
    createSetters = false
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}


dependencies {
    api "org.apache.avro:avro:${avroVersion}"
}

sourceSets {
    main {
        java {
            srcDir "$buildDir/generated/src/main/java"
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }
    repositories {
        maven {
            name = "nexus"
            url = uri("http://localhost:7777/repository/maven-releases/")
            allowInsecureProtocol = true
            credentials {
                username = project.findProperty("nexusUser") ?: "admin"
                password = project.findProperty("nexusPassword") ?: "admin123"
            }
        }
    }
}
