{
  "type": "record",
  "name": "DeviceError",
  "namespace": "com.nashkod.avro",
  "fields": [
    {
      "name": "failedEvent",
      "type": "com.nashkod.avro.Device"
    },
    {
      "name": "errorMeta",
      "type": {
        "type": "record",
        "name": "ErrorMeta",
        "fields": [
          { "name": "errorSource", "type": "string" },
          { "name": "reason", "type": "string" },
          { "name": "stackTrace", "type": "string" }
        ]
      }
    },
    {
      "name": "receivedAt",
      "type": "long"
    }
  ]
}
